In [1]:
import numpy as np
import math
from datascience import *
import country_converter as cc
from autocorrect import Speller as sp
from array import *
from geotext import GeoText
from spellchecker import SpellChecker
import re
tbl = Table.read_table('../2021_Results.csv')
countries = list(tbl.column("Country"))
st = list(tbl.column("State"))
cities = list(tbl.column("City"))
spell = sp(lang='en')
s = SpellChecker()
#tbl
table_copy = tbl

In [2]:
def standardize_countries(table):
    
    usa_vars = make_array( 'Usa','Us', 'US','Hartford','California','America','San Francisco','The United States','U S', 'UNITED STATES', 'USA',
           'USA (company is based in a Up territory, I work remote)',
           'USA tomorrow', "USA, but for foreign gov't", 'USA-- Virgin Islands','Unite States',
           'United  States','United State',
           'United State of America', 'United States',
           'United States (I work from home and my clients are all over the Up/Canada/X',
           'United States Of America', 'United States of America',
           'United States of American', 'United States of Americas',
           'United States of america', 'United States- Puerto Rico',
           'United Statues', 'United Status','United state', 'United states', 'United states of America',
           'United states of america', 'United y', 'UnitedStates', 'Us', 'Usa', 'Use','Virginia','america','united States', 'united stated', 'united states', 'united states of america','us', 'usa', 'üá∫üá∏',)
    netherlands_vars = make_array('Netherlands','The Netherlands',  'The netherlands', 'netherlands','the Netherlands','the netherlands','Nederland')
    not_specified = make_array('I Work For A A-Based Organization, Though I Am Personally In The Up','Not specified/unclear response', 'Canada and usa','International',   'For the United States government, but posted overseas','From New Zealand but on projects across A', 'Worldwide (based in Up but short term trips around the world)','X', 'Y', 'Z', 'n/a (remote from wherever I want)', "I earn commission on sales If I meet quota, I'm guaranteed another 16k min Last year i earned an additional 27k It's not uncommon for people in my space to earn 100k+ after commission",
           'I was brought in on this salary to help with the He and very quickly was promoted to current position but compensation was not altered','S','A', "We don't get raises, we get quarterly bonuses, but they periodically passes income in the area you work, so I got a raise because a 3rd party assessment showed I was paid too little for the area we were locate", 'bonus based on meeting yearly goals set w/ my supervisor','$2,17584/year is deducted for benefits','Contracts','Global','E',   'Currently finance', 'europe','Remote (philippines)')
    uk_only = make_array( "I Work For An Up Based Company But I'M From Argentina",'From Romania, But For An Up Based Company', 'Austria, But I Work Remotely For A Dutch/British Company','I Am Located In Canada But I Work For A Company In The Up', 'Uk', 'United Kingdom', 'United kingdom','united kingdom', 'uk', 'up','Up for Up company','The Up', 'Up govt employee overseas, country withheld',
           'Up, but for globally fully remote company', 'Up, remote', 'Up>','Up')
    england = make_array( 'England', 'England, Gb', 'England, United Kingdom', 'England, Up', 'England/Up','United Kingdom (England)', 'Up (England)', 'Up (northern England)', 'england','Up of A',)
    wales =make_array( 'Wales',
           'Wales (united kingdom)', 'Wales (up)', 'Wales, up',)
    n_ireland = make_array('Northern ireland',
             'Northern ireland, united kingdom','Up (Northern Ireland)',)
    nz=make_array('Aotearoa New Zealand', 'New Zealand',
           'New Zealand Aotearoa',)
    canada = make_array('Can', 'Canada',
           'Canada, Ottawa, Ontario',)

    spell = sp(lang="en")
    for country in range(len(countries)):
        countries[country] = countries[country].replace(".","").strip()
        countries[country] = spell(countries[country])
        countries[country] = countries[country].title()
        if countries[country] == 'Trinidad And Tobacco':
            countries[country] = "Trinidad and Tobago"

        if countries[country] == 'Mainland China':
            countries[country] = "China"
        if countries[country] == 'Japan, Up Gov Position':
            countries[country] = "Japan"
        if countries[country] == 'Scotland, Up':
            countries[country] = "Scotland"
        if countries[country] == 'Australian':
            countries[country] = "Australia"
        if countries[country] ==  'Luxemburg':
            countries[country] = 'Luxembourg'
        if countries[country] ==  'The Bananas':
            countries[country] = 'The Bahamas'
        if countries[country] ==  'Param√°':
            countries[country] = 'Panama'
        if countries[country] ==  'Is':
            countries[country] = 'Iceland'
        if countries[country] ==  'Brasil':
            countries[country] = 'Brazil'
        if countries[country] ==  'M√©xico':
            countries[country] = 'Mexico'
        if countries[country] ==  "C√¥te D'Voice":
            countries[country] = 'Ivory Coast'
        if countries[country] ==  'In':
            countries[country] = 'India'
        if countries[country] ==  'Danmark':
            countries[country] = 'Denmark'
        if countries[country] ==  'Jersey, Channel Islands':
            countries[country] = 'Jersey'
        if countries[country] ==   'Argentina T M R In In Thailand':
            countries[country] = 'Thailand'
        if countries[country] ==  'Italy (South)':
            countries[country] = 'Italy'
        if countries[country] in usa_vars:
            countries[country] = "United States of America"
        if countries[country] in netherlands_vars:
            countries[country] = "Netherlands"
        if countries[country] in uk_only:
            countries[country] = "United Kingdom"
        if countries[country] == 'Us':
            countries[country] = "United States of America"
        if countries[country] in england:
            countries[country] = "England"
        if countries[country] in wales:
            countries[country] = "Wales"
        if countries[country] in canada:
            countries[country] = "Canada"
        if countries[country] in n_ireland:
            countries[country] = "Northern Ireland"
        if countries[country] in nz:
            countries[country] = "New Zealand"
        if countries[country] in not_specified:
            countries[country] = ""



    table.column("Country") == countries
    x =table.where("Country",are.equal_to("United Kingdom"))
    for i in range(len(countries)):

        if countries[i] == "United Kingdom" and st[i] != "nan" :

            countries.pop(i)
            countries.insert(i,"United States of America")  


    table = table.append_column( "Country", countries)
   
    
    return table

In [3]:
def standardize_states(table):

    spell = sp(lang='en')
    for s in range(len(st)):
        st[s] = st[s].replace(".","").strip()
        st[s]= spell(st[s])
        st[s] = st[s].title()
        if "," in st[s]:
            st.pop(s)
            st.insert(s,"")
        if st[s] == "Nan":
            st.pop(s)
            st.insert(s,"")

   # unique_states = np.unique(st)
    table = table.with_column("State", st)
    return table

In [4]:
## this method checks if a certain string contains no alphanumeric characters.
def no_alphanumeric(str):
    l = len(str)
    count =0
    for letter in str:
        if not letter.isalnum():
            count = count +1
    if l == count:
        return True
    else:
        return False
## this method checks if a certain string contains only number characters.
def only_numbers(str):
    l = len(str)
    count =0
    for letter in str:
        if  letter.isdecimal():
            count = count +1
    if l == count:
        return True
    else:
        return False

In [5]:



def standardize_cities(table):
    
    misspelled = s.unknown(cities)
    commas = []
    for c in range(len(cities)):
        cities[c] = cities[c].replace(".","").strip()
        if len(cities[c]) >= 25:
            cities[c] = ""
        if no_alphanumeric(cities[c]):
            cities[c] = ""
        if only_numbers(cities[c]):
            cities[c] = ""
        if "indenti" in cities[c]:
            cities[c] = ""
        if "Indenti" in cities[c]:
            cities[c] = ""
        if "(" in cities[c]:
           #commas.append(cities[c])
            #print(cities[c])
            #print('---------')
            x = cities[c].find("(")
            cities[c] = cities[c][:x]
            #print(cities[c])
        if cities[c] == 'Washington, DC':
            cities[c] = "Washington DC"
        if "," in cities[c]:
            x2 = cities[c].find(",")
            cities[c] = cities[c][:x2]
        if "prefer" in cities[c]:
           # print(cities[c])
            cities[c] = ""  
        if "Prefer" in cities[c]:
           # print(cities[c])
            cities[c] = ""
        if "remote" in cities[c]:
           # print(cities[c])
            cities[c] = ""
        if "Remote" in cities[c]:
           # print(cities[c])
            cities[c] = ""
            commas.append(cities[c])
    #print(commas)
    #print(np.unique(cities))
    table = table.with_column("City",cities)
    return table

In [7]:




x =standardize_countries(table_copy)
x = standardize_states(x)
x = standardize_cities(x)
x.where("Country", are.equal_to("")).show(100
      )